@startuml reg-manager
'https://plantuml.com/class-diagram
skinparam classAttributeIconSize 0

'Classes
abstract AbstractPeriphery {
    #AbstractPeriphery(std::shared_ptr<HwInterface> hw_interface,
    std::shared_ptr<ProtocolInterface> protocol_interface)
    -std::shared_ptr<HwInterface> hw_interface_;
    -std::shared_ptr<ProtocolInterface> protocol_interface_;
    -writeData(const std::vector<uint8_t> data) : void
    -readData() : std::vector<uint8_t>
    +getDataSyncroniously(std::vector<uint8_t> &tx_data) : uint8_t
    +{abstract}init() : uint8_t
    +{abstract}deinit() : uint8_t
    +{abstract}getStatus() : uint8_t
}

class SensorMock {
    +SensorMock(std::shared_ptr<HwInterface> hw_interface,
        std::shared_ptr<ProtocolInterface> protocol_interface)
    +init() : uint8_t
    +deinit() : uint8_t
    +getStatus() : uint8_t
}

class TemperatureSensor {
    +TemperatureSensor(std::shared_ptr<HwInterface> hw_interface,
        std::shared_ptr<ProtocolInterface> protocol_interface)
    +init() : uint8_t
    +deinit() : uint8_t
    +getStatus() : uint8_t
    +getTemperature() : uint8_t
}

class DayCamera {
    +DayCamera(std::shared_ptr<HwInterface> hw_interface,
        std::shared_ptr<ProtocolInterface> protocol_interface)
    +init() : uint8_t
    +deinit() : uint8_t
    +getStatus() : uint8_t
    +getZoom() : uint8_t
    +zoomIn() : uint8_t
    +zoomOut() : uint8_t
}

class ThermalCamera {
    +ThermalCamera(std::shared_ptr<HwInterface> hw_interface,
        std::shared_ptr<ProtocolInterface> protocol_interface)
    +init() : uint8_t
    +deinit() : uint8_t
    +getStatus() : uint8_t
    +getZoom() : uint8_t
    +zoomIn() : uint8_t
    +zoomOut() : uint8_t
    +changePolarity() : uint8_t
}

interface HwInterface {
    +{abstract} write(const std::vector<uint8_t>& data) : void
    +{abstract} read() : std::vector<uint8_t>
}

class HwMock {
    +write(const std::vector<uint8_t>& data) : void
    +read() : std::vector<uint8_t>
}

class Uart {
    +write(const std::vector<uint8_t>& data) : void
    +read() : std::vector<uint8_t>
}

class Ethernet {
    +write(const std::vector<uint8_t>& data) : void
    +read() : std::vector<uint8_t>
}

interface ProtocolInterface {
    +{abstract}packData(const std::vector<uint8_t>& data) : std::vector<uint8_t>
    +{abstract}unpackData(const std::vector<uint8_t>& data) : std::vector<uint8_t>
}

class TemperatureSensorProtocol {
    +packData(const std::vector<uint8_t>& data) : std::vector<uint8_t>
    +unpackData(const std::vector<uint8_t>& data) : std::vector<uint8_t>
}

class ProtocolMock {
    +packData(const std::vector<uint8_t>& data) : std::vector<uint8_t>
    +unpackData(const std::vector<uint8_t>& data) : std::vector<uint8_t>
}

object UserCode {
    auto protocol_interface = std::make_shared<ProtocolMock>();
    auto hw_interface = std::make_shared<HwMock>();
    auto temp_sensor = std::make_shared<SensorMock>(hw_interface, protocol_interface);
    \n
    temp_sensor->init();
    std::cout << static_cast<int>(temp_sensor->getStatus()) << std::endl;
    std::cout << static_cast<int>(temp_sensor->getTemperature()) << std::endl;
    std::cout << static_cast<int>(temp_sensor->getHumidity()) << std::endl;
    temp_sensor->deinit();
}

'Relations
HwMock -up-|> HwInterface
Uart -up-|> HwInterface
Ethernet -up-|> HwInterface

TemperatureSensorProtocol -up-|> ProtocolInterface
ProtocolMock -up-|> ProtocolInterface

AbstractPeriphery "Strategy" o-- HwInterface
AbstractPeriphery "Strategy" o-- ProtocolInterface

SensorMock -up-|> AbstractPeriphery
TemperatureSensor -up-|> AbstractPeriphery
DayCamera -up-|> AbstractPeriphery
ThermalCamera -up-|> AbstractPeriphery

'Notes

@enduml
