@startuml reg-manager
'https://plantuml.com/class-diagram
skinparam classAttributeIconSize 0

'Classes

interface LoggerInterface {
}

class Logger {
}

class SpdLogAdapter {
}

class StdoutAdapter {
}

abstract AbstractPeriphery {
    #AbstractPeriphery(std::shared_ptr<CommunicationInterface> communication_interface, std::shared_ptr<ProtocolInterface> protocol_interface)
    -std::shared_ptr<CommunicationInterface> communication_interface_;
    -std::shared_ptr<ProtocolInterface> protocol_interface_;
    -writeData(const std::vector<uint8_t> data) : void
    -readData() : std::vector<uint8_t>
    +getDataSyncroniously(std::vector<uint8_t> &tx_data) : uint8_t
    +{abstract}init() : uint8_t
    +{abstract}deinit() : uint8_t
    +{abstract}getStatus() : uint8_t
}

class SensorMock {
    +SensorMock(std::shared_ptr<CommunicationInterface> communication_interface, std::shared_ptr<ProtocolInterface> protocol_interface)
    +init() : uint8_t
    +deinit() : uint8_t
    +getStatus() : uint8_t
}

class TemperatureSensor {
    +TemperatureSensor(std::shared_ptr<CommunicationInterface> communication_interface, std::shared_ptr<ProtocolInterface> protocol_interface)
    +init() : uint8_t
    +deinit() : uint8_t
    +getStatus() : uint8_t
    +getTemperature() : uint8_t
}

interface CommunicationInterface {
    +{abstract} write(const std::vector<uint8_t>& data) : void
    +{abstract} read() : std::vector<uint8_t>
}

class CommunicationMock {
    +write(const std::vector<uint8_t>& data) : void
    +read() : std::vector<uint8_t>
}

class Uart {
    +write(const std::vector<uint8_t>& data) : void
    +read() : std::vector<uint8_t>
}

class Ethernet {
    +write(const std::vector<uint8_t>& data) : void
    +read() : std::vector<uint8_t>
}

interface ProtocolInterface {
    +{abstract}packData(const std::vector<uint8_t>& data) : std::vector<uint8_t>
    +{abstract}unpackData(const std::vector<uint8_t>& data) : std::vector<uint8_t>
}

class TemperatureSensorProtocol {
    +packData(const std::vector<uint8_t>& data) : std::vector<uint8_t>
    +unpackData(const std::vector<uint8_t>& data) : std::vector<uint8_t>
}

class ProtocolMock {
    +packData(const std::vector<uint8_t>& data) : std::vector<uint8_t>
    +unpackData(const std::vector<uint8_t>& data) : std::vector<uint8_t>
}

object UserCode {
    auto communication_interface = std::make_shared<CommunicationMock>();
    auto protocol_interface = std::make_shared<TemperatureSensorProtocol>();
    auto temp_sensor = std::make_shared<TemperatureSensor>(communication_interface, protocol_interface);
    \n
    temp_sensor->init();
    LOG_INFO("{}", temp_sensor->getStatus());
    LOG_INFO("{}", temp_sensor->getTemperature());
    SET_LOG_LEVEL(LoggerInterface::LogLevel::Debug);
    LOG_INFO("{}", temp_sensor->getHumidity());
    \n
    temp_sensor->deinit();
}

'Relations
CommunicationMock -up-|> CommunicationInterface
Uart -up-|> CommunicationInterface
Ethernet -up-|> CommunicationInterface

TemperatureSensorProtocol -up-|> ProtocolInterface
ProtocolMock -up-|> ProtocolInterface

AbstractPeriphery "Strategy" o-- CommunicationInterface
AbstractPeriphery "Strategy" o-- ProtocolInterface

Logger -up-> LoggerInterface
Logger -up-> SpdLogAdapter
SpdLogAdapter .up.|> LoggerInterface
StdoutAdapter .up.|> LoggerInterface

SensorMock -up-|> AbstractPeriphery
TemperatureSensor -up-|> AbstractPeriphery

'Notes

@enduml
